language: objective-c  #1
osx_image: xcode7.3 #2

cache: cocoapods

install:
  - pod repo update > /dev/null
  - pod install

script:
  - xctool -workspace RNDApp.xcworkspace -scheme RNDApp -sdk iphonesimulator build test
