language: objective-c  #1
osx_image: xcode7.3 #2
#xcode_workspace: ./Tykoon/Tykoon.xcworkspace #3
xcode_workspace: RNDApp.xcworkspace #3
xcode_scheme: RNDApp #4
xcode_sdk: iphonesimulator9.2 #5

install:
  - pod repo update
  - pod install
