language: objective-c
osx_image: xcode7.3

cache: cocoapods

install:
  - pod repo update > /dev/null
  - pod install

script:
  - xctool -workspace RNDApp.xcworkspace -scheme RNDApp -sdk iphonesimulator build test
